[package]
name = "Rust Project Template" 
created_by = ["Haliunaa Munkhuu"]
language = "en"
multilingual = false
src = "src"
title = "Rust Project Template"
version = "0.1.0"
edition = "2018" 

[dependencies]